### ISSUE TITLE
Mark L1, L2, L3 Progress

### ISSUE THREAD

**Issue by klappy** [unfoldingWord-dev/ts-requirements#172]
As a user I want to label chunk progress as L1, L2, L3 and not just marked as done so that I can keep track of their progress.
- [ ] Define how data would be stored
- [ ] Design how UI will look

**Comment by da1nerd** [comment]
@jag3773 we need to consider this in the update to the Resource Container spec.

**Comment by jag3773** [comment]
@neutrinog @klappy I'd suggest that we use the USFM spec for this. In particular, the USFM 3 spec which allows for milestones and attributes within those milestones: http://ubsicap.github.io/usfm/milestones/index.html.

This is a broad proposal that would require we
- [ ] Implement milestones for our chunk markers
- [ ] Use an attribute on each of the above that could record the stage that it is at

My opinion is that the Resource Container spec (v0.1) is overstepping it's bounds with reference to Scripture.  In other words, for Scripture, the Resource Container manifest should essentially have a mimetype that says the content inside is USFM.  From there on out it's up to the USFM processor of whatever app is in question to handle the USFM properly..

**Comment by da1nerd** [comment]
That sounds great for Bible. But what about obs which is in markdown?
